/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ceres_QuadDoubleInterface */

#ifndef _Included_ceres_QuadDoubleInterface
#define _Included_ceres_QuadDoubleInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ceres_QuadDoubleInterface
 * Method:    fpuFixStart
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ceres_QuadDoubleInterface_fpuFixStart
  (JNIEnv *, jclass);

/*
 * Class:     ceres_QuadDoubleInterface
 * Method:    fpuFixEnd
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ceres_QuadDoubleInterface_fpuFixEnd
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ceres_QuadDoubleInterface
 * Method:    add
 * Signature: (DDDDDDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ceres_QuadDoubleInterface_add
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ceres_QuadDoubleInterface
 * Method:    sub
 * Signature: (DDDDDDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ceres_QuadDoubleInterface_sub
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ceres_QuadDoubleInterface
 * Method:    mult
 * Signature: (DDDDDDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ceres_QuadDoubleInterface_mult
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ceres_QuadDoubleInterface
 * Method:    div
 * Signature: (DDDDDDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ceres_QuadDoubleInterface_div
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ceres_QuadDoubleInterface
 * Method:    sqrt
 * Signature: (DDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ceres_QuadDoubleInterface_sqrt
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ceres_QuadDoubleInterface
 * Method:    log
 * Signature: (DDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ceres_QuadDoubleInterface_log
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ceres_QuadDoubleInterface
 * Method:    exp
 * Signature: (DDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ceres_QuadDoubleInterface_exp
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ceres_QuadDoubleInterface
 * Method:    pow
 * Signature: (DDDDDDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ceres_QuadDoubleInterface_pow
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ceres_QuadDoubleInterface
 * Method:    cos
 * Signature: (DDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ceres_QuadDoubleInterface_cos
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ceres_QuadDoubleInterface
 * Method:    sin
 * Signature: (DDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ceres_QuadDoubleInterface_sin
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ceres_QuadDoubleInterface
 * Method:    tan
 * Signature: (DDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ceres_QuadDoubleInterface_tan
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ceres_QuadDoubleInterface
 * Method:    acos
 * Signature: (DDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ceres_QuadDoubleInterface_acos
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ceres_QuadDoubleInterface
 * Method:    asin
 * Signature: (DDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ceres_QuadDoubleInterface_asin
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ceres_QuadDoubleInterface
 * Method:    atan
 * Signature: (DDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ceres_QuadDoubleInterface_atan
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ceres_QuadDoubleInterface
 * Method:    toString
 * Signature: (IDDDD)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ceres_QuadDoubleInterface_toString
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
