/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ceres_common_DirectedRounding */

#ifndef _Included_ceres_common_DirectedRounding
#define _Included_ceres_common_DirectedRounding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ceres_common_DirectedRounding
 * Method:    addUp
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_ceres_common_DirectedRounding_addUp
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     ceres_common_DirectedRounding
 * Method:    addDown
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_ceres_common_DirectedRounding_addDown
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     ceres_common_DirectedRounding
 * Method:    subUp
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_ceres_common_DirectedRounding_subUp
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     ceres_common_DirectedRounding
 * Method:    subDown
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_ceres_common_DirectedRounding_subDown
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     ceres_common_DirectedRounding
 * Method:    multUp
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_ceres_common_DirectedRounding_multUp
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     ceres_common_DirectedRounding
 * Method:    multDown
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_ceres_common_DirectedRounding_multDown
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     ceres_common_DirectedRounding
 * Method:    divUp
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_ceres_common_DirectedRounding_divUp
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     ceres_common_DirectedRounding
 * Method:    divDown
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_ceres_common_DirectedRounding_divDown
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     ceres_common_DirectedRounding
 * Method:    sqrtDown
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_ceres_common_DirectedRounding_sqrtDown
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ceres_common_DirectedRounding
 * Method:    sqrtUp
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_ceres_common_DirectedRounding_sqrtUp
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ceres_common_DirectedRounding
 * Method:    addRoundoff
 * Signature: (DDDD)D
 */
JNIEXPORT jdouble JNICALL Java_ceres_common_DirectedRounding_addRoundoff
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ceres_common_DirectedRounding
 * Method:    computeZeta
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_ceres_common_DirectedRounding_computeZeta
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     ceres_common_DirectedRounding
 * Method:    computeDelta
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_ceres_common_DirectedRounding_computeDelta
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     ceres_common_DirectedRounding
 * Method:    addRoundoffAtimesBplusC
 * Signature: (DDDD)D
 */
JNIEXPORT jdouble JNICALL Java_ceres_common_DirectedRounding_addRoundoffAtimesBplusC
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ceres_common_DirectedRounding
 * Method:    addRoundoffABplusCD
 * Signature: (DDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_ceres_common_DirectedRounding_addRoundoffABplusCD
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
